version: '3'
services:
  # SQL Server Docker Container
  sql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    restart: unless-stopped
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=GymFit123!
      - MSSQL_PID=Developer
    ports:
      - 1435:1433
    networks:
      - gymfitnetwork

  # ASP.NET Core Application Docker Container
  api:
    restart: unless-stopped
    build:
      context: .
      dockerfile: GymFit.Api\Dockerfile
    environment:
      - ConnectionStrings:Main=Server=sql,1433;Database=GymFitdocker;User=sa;Password=GymFit123!;TrustServerCertificate=True;ConnectRetryCount=0
    ports:
      - 8080:80
    networks:
      - gymfitnetwork
    links:
      - sql
    depends_on:
      - sql
networks:
  gymfitnetwork:
    driver: bridge
